<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
	'Content' => 'Контент',
	'Stocks' => 'Акции',
	'Stocks list' => 'Список акций',
	'Create time' => 'Время создания',
	'Update time' => 'Время обновления',
	'Date' => 'Дата',
	'Title actions' => 'Заголовок акции',
	'Slug' => 'Алиас',
	'Image stocks' => 'Изображение акции',
	'Language' => 'Язык',
	'Short text' => 'Короткий текст',
	'Full text' => 'Полный текст',
	'Status' => 'Статус',
	'Seo description' => 'Seo описание',
	'Draft' => 'Черновик',
	'Published' => 'Опубликовано',
	'On moderation' => 'На модерации',
	'Control' => 'Управление',
	'Stocks - control' => 'Акции - управление',
	'Control stocks' => 'Управление акциями',
	'Add stock' => 'Добавить акцию',
	'Search stocks' => 'Поиск акций',
	'Edit stock' => 'Редактировать акцию',
	'Views stock' => 'Просмотреть акцию',
	'Delete stock' => 'Удалить акцию',
	'Are you sure you want to remove the tag?' => 'Вы уверены, что хотите удалить тег?',
	'Edit' => 'Редактирование',
	'stock' => 'акции',
	'Stock' => 'Акция',
	'View' => 'Просмотреть',
	'Search stock' => 'Искать акцию',
	'Fields marked' => 'Поля, отмеченные',
	'required' => 'обязательны',
	'Name badge' => 'Название значка',
	'Color background badge' => 'Цвет фона значка',
	'Background stock' => 'Фон акции',
	'Online store stock module' => 'Модуль акций интернет магазина',
	'Manage stocks' => 'Управление акциями',
	'Creating stock' => 'Создать акцию',
	'Removing stock' => 'Удалить акцию',
	'List of stocks' => 'Список акций',
	'Editing stocks' => 'Редактирование акций',
	'Viewing stocks' => 'Просмотр акций',
	'Stocks settings' => 'Настройка акций',
	'General module settings' => 'Главные настройки модуля',
	'Minimum size (in bytes)' => 'Минимальный размер (в байтах)',
	'Maximum size (in bytes)' => 'Максимальный размер (в байтах)',
	'Accepted extensions (separated by comma)' => 'Допустимые расширения (через запятую)',
	'Uploading files catalog (relatively {path})' => 'Папка для загрузки файлов (относительно {path})',
	'Visual editor' => 'Визуальный редактор',
	'This section provides a list of stocks' => 'В этом разделе представлен список акций',
	'Date' => 'Дата',
	'Date' => 'Дата',
	'Date' => 'Дата',
];